export const aaa = [
  { name: 'スタート' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
  { name: 'aaa' },
];
