export const aaa = [
  { eatName: 'たらこ' },
  { eatName: 'いくら' },
  { eatName: 'サーモン' },
  { eatName: '納豆' },
  { eatName: 'りんご' },
  { eatName: 'バナナ' },
  { eatName: 'いちご' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
];
