export const aaa = [
  { eatName: 'スタート' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
  { eatName: 'aaa' },
];
